git:
  depth: 10
language: ruby

rvm:
  - 2.0.0
  - 2.2.3

sudo: false

cache: bundler

gemfile: Gemfile

bundler_args: --without development --deployment

before_script:
  - cd dashboard
  - bundle exec rake -t db:create db:schema:load

script:
  - bundle exec rake -t test test:benchmark
  - PEGASUS_DB_NAME=pegasus_test DASHBOARD_DB_NAME=dashboard_test PATH_TO_HIT=/hoc/1 bundle exec derailed exec perf:ips

env:
  - DB=mysql
