# Docker Compose file for running ui tests.
#
# To run, set the following env variables (values obtainable from Circle):
# PROPERTIES_ENCRYPTION_KEY
# CLOUDFRONT_KEY_PAIR_ID
# CLOUDFRONT_PRIVATE_KEY
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# APPLITOOLS_KEY
# FIREBASE_NAME
# FIREBASE_SECRET
# SAUCE_USERNAME
# SAUCE_ACCESS_KEY
#
# then run:
# docker-compose -f ui-tests-compose.yml up
# 
# To clean up:
# docker-compose -f ui-tests-compose.yml down

version: '3'
services:
  site:
    image: wintercdo/code-dot-org:0.6
    volumes:
      - .:/home/circleci/code-dot-org
      - bundleconfig:/home/circleci/code-dot-org/.bundle
      - dashboardtmp:/home/circleci/code-dot-org/dashboard/tmp
      - nodemodules:/home/circleci/code-dot-org/apps/node_modules
      - bundledeps:/home/circleci/project/vendor/bundle
      - mysqldata:/var/lib/mysql
    env_file:
      - docker_tests/env.list
    command: /bin/sh -c "cd /home/circleci/code-dot-org; docker_tests/ui_tests.sh"

  ui-tests-redis:
    image: redis

volumes:
  nodemodules:
  bundledeps:
  bundleconfig:
  dashboardtmp:
  mysqldata:

