# Docker Compose file for running unit tests.
#
# To run:
# docker-compose -f unit-tests-compose.yml up
# To clean up:
# docker-compose -f unit-tests-compose.yml down

version: '3'
services:
  site:
    image: wjordan/code-dot-org:0.5
    volumes:
      - .:/home/circleci/code-dot-org
      - bundleconfig:/home/circleci/code-dot-org/.bundle
      - dashboardtmp:/home/circleci/code-dot-org/dashboard/tmp
      - nodemodules:/home/circleci/code-dot-org/apps/node_modules
      - bundledeps:/home/circleci/project/vendor/bundle
      - mysqldata:/var/lib/mysql
    env_file:
      - docker_tests/env.list
    command: /bin/sh -c "cd /home/circleci/code-dot-org; docker_tests/unit_tests.sh"

volumes:
  nodemodules:
  bundledeps:
  bundleconfig:
  dashboardtmp:
  mysqldata:
