---
# Uses the ec2 driver by default through symlink in .kitchen.local.yml
transport:
  name: sftp
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.7.2
platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
suites:
  - name: default
    run_list:
      - recipe[cdo-discourse]
