---
transport:
  name: sftp
driver:
  name: docker
  use_sudo: false
  volume:
    - /var/run/docker.sock:/var/run/docker.sock # Reuse host docker service within docker container
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.7.2
platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    attributes:
      cdo-discourse:
        port: 8080
suites:
  - name: default
    run_list:
      - recipe[cdo-discourse]
