version: 0.2
env:
  variables:
    REPO_NAME: cdo

phases:
  pre_build:
    commands:
      - >
        export REPO_URL=$(
          aws ecr describe-repositories \
            --repository-name ${REPO_NAME} \
            --query repositories[0].repositoryUri \
            --output text
        )
      - export REPO_TAG=${REPO_URL}:${CODEBUILD_SOURCE_VERSION}
      - docker version
      - $(aws ecr get-login --no-include-email)
      - docker pull ${REPO_TAG} || true
  build:
    commands:
      - >
        cd .circleci && docker build \
          --cache-from ${REPO_TAG} \
          --tag ${REPO_TAG}
          .
  post_build:
    commands:
      - docker push ${REPO_URL}
