---
transport:
  name: ssh_tgz
driver:
  name: docker
  use_sudo: false
  privileged: true
provisioner:
  name: chef_zero
  require_chef_omnibus: 11.18.12
platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    attributes:
      cdo-apps:
        dashboard:
          port: 8080
        pegasus:
          port: 8081
suites:
  - name: default
    run_list:
      - recipe[nginx_test]
