---
driver:
  name: dokken
  chef_version: 15.2.20
transport:
  name: dokken
provisioner:
  name: dokken
  chef_license: accept
platforms:
  - name: ubuntu-18.04
    run_list:
      - recipe[apt]
      - recipe[sudo-user]
suites:
  - name: default
    run_list:
      - recipe[cdo-ruby]
verifier:
  name: inspec
