---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[cdo-ruby]
  - name: '2-2'
    run_list:
      - recipe[apt]
      - recipe[cdo-ruby]
    attributes:
      version: '2.2'
      bundler_version: '1.10.6'
  - name: '2-2-upgrade'
    run_list:
      - recipe[apt]
      - recipe[cdo-ruby::2.0]
      - recipe[cdo-ruby]
    attributes:
      version: '2.2'
      bundler_version: '1.10.6'
