---
transport:
  name: ssh_tgz
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  require_chef_omnibus: 11.18.12
  environments_path: test/environments
  client_rb:
    node_name: test_cdo-apps
    environment: adhoc
platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
suites:
  - name: default
    run_list:
      - recipe[cdo-repository]
