---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[varnish_test]
    attributes:
      cdo-apps:
        dashboard:
          port: 8080
        pegasus:
          port: 8081
        i18n:
          languages:
            en: English
            fr: French
