---
driver:
  name: docker
  use_sudo: false
  volume:
    - <%= File.absolute_path(File.join(__dir__, '..', '..')) %>:/home/kitchen/adhoc # Reuse host repo instead of new checkout
    - <%= ENV['OMNIBUS_PATH'] || '/tmp/chef_omnibus' %>:/tmp/chef_omnibus # cache chef omnibus download/install
transport:
  name: sftp
  connection_timeout: 10
  connection_retries: 5
provisioner:
  name: chef_zero
  require_chef_omnibus: 11.18.12
  chef_omnibus_install_options: -d /tmp/chef_omnibus # cache chef omnibus download/install
  environments_path: test/environments
  client_rb:
    node_name: test_cdo-apps
    environment: adhoc
platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    attributes:
      cdo-repository:
        branch: <%= `git rev-parse --abbrev-ref HEAD` %>
suites:
  - name: default
    run_list:
      - recipe[cdo-mysql::server]
      - recipe[cdo-apps]
