---
driver:
  name: ec2
  region: us-west-2
  aws_ssh_key_id: server_access_key
  security_group_ids: ["sg-af6d98c8"]
  subnet_id: subnet-404a7937
  instance_type: m3.2xlarge
  image_search:
    name: cdo-*
    virtualization-type: hvm
    root-device-type: ebs
    block-device-mapping.volume-type: gp2
  block_device_mappings:
    - ebs_device_name: /dev/sda1
      ebs_volume_size: 64
      ebs_delete_on_termination: true
      ebs_volume_type: gp2
  duration: 120
  price: 2
  retryable_tries: 60
  retryable_sleep: 10
