---
driver:
  name: docker
  use_sudo: false
  volume:
    - <%= File.absolute_path(File.join(__dir__, '..', '..')) %>:/home/kitchen/adhoc # Reuse host repo instead of new checkout
transport:
  name: sftp
  connection_timeout: 10
  connection_retries: 5
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0
  environments_path: test/environments
  client_rb:
    node_name: test_cdo-apps
    environment: adhoc
platforms:
  - name: ubuntu-14.04
    driver_config:
      image: wjordan/ubuntu-chef:12.6.0
    attributes:
      cdo-repository:
        branch: <%= `git rev-parse --abbrev-ref HEAD` %>
suites:
  - name: default
    run_list:
      - recipe[cdo-apps]
